[package]
edition = "2021"
name = "ngrok-js"
version = "0.0.9"

[lib]
crate-type = ["cdylib"]

[dependencies]
async-trait = "0.1.59"
bytes = "1.3.0"
futures-util = "0.3.26"
lazy_static = "1.4.0"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.10.6", default-features = false, features = ["napi4", "tokio_rt"] }
napi-derive = "2.9.3"
ngrok = { path = "../ngrok-rs/ngrok" }
parking_lot = "0.12.1"
tokio = { version = "1.23.0", features = ["sync"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
url = "2.3.1"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
